export const CREATE_CATEG0RY = "CREATE_CATEG0RY";
export const CREATE_CATEG0RY_SUCCESS = "CREATE_CATEG0RY_SUCCESS";
export const CREATE_CATEG0RY_FAILURE = "CREATE_CATEG0RY_FAILURE";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIEs_FAILURE";
